version: '3.0'

services:
    
  main:
    container_name: main-ictis
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
    - 5000:5000
    - 3333:3333
    restart: on-failure    
    command: npm start
    depends_on:
      - postgres
  postgres:
    container_name: postgres-ictis

    image: postgres:12 
    env_file:
    - .env
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 6432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes: 
  pgdata: