version: '3.0'

services:
    
  main:
    container_name: main-ictis
    stdin_open: true
    build:
      context: .
    env_file:
      - .env.local
    volumes:
      - .:/app  
      - /app/node_modules
    ports:
      - 5001:5000
      - 4200:4200
      - 4400:4400
    restart: on-failure    
    command: npm start
    depends_on:
      - postgres
  postgres:
    container_name: postgres-ictis

    image: postgres:12 
    env_file:
      - .env.local
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 6432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes: 
  pgdata: