name: Telegram nofity commit
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_TO_SERGEYDT }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Ref: ${{ github.event.ref }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
